version: '3.7'
services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '35432:5432'
        networks:
          - app-network
        volumes: 
          - ./Postgres:/tmp
          - ./postgres-db:/var/lib/postgresql/data
          - ./Postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    api:
        build: ./API
        depends_on:
        - postgres
        image: api
        container_name: api
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
          - API_PORT=8000
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '9000:8000'
        networks:
          - app-network
    app:
        build: ./basketball
        depends_on:
        - postgres
        image: app
        container_name: app
        restart: always
        environment:
          - REACT_APP_POSTGRES_URL=http://api:9000/
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '3000:3000'
        networks:
          - app-network
networks:
  app-network:
    name: app-network